---
- hosts: local
  become: true
  tasks:
    - name: install java
      apt:
        name:
          - openjdk-8-jdk
        state: present
    - name: install docker
      apt:
        pkg: docker.io
        state: present
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true
    - name: deploy the application
      command: sudo docker run -it -d -p 8888:8888 ksauto82/casestudy:1.0
  handlers:
  - name: run update
    apt:
      update_cache: yes
...
